# Generated by Django 3.1.3 on 2023-09-25 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactos',
            fields=[
                ('IdCliente', models.CharField(default='Sin Dato', max_length=80)),
                ('IdContacto', models.CharField(default='0000000', max_length=80, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(default='Sin Dato', max_length=40)),
                ('SegundoNombre', models.CharField(default='Sin Dato', max_length=40)),
                ('Apellidos', models.CharField(default='Sin Dato', max_length=100)),
                ('Principal', models.BooleanField(default=False)),
                ('CorreoElectronico', models.CharField(default='mail@hitec.com', max_length=400)),
                ('Telefono', models.CharField(default='Sin Dato', max_length=40)),
                ('TelefonoMovil', models.CharField(default='Sin Dato', max_length=40)),
                ('Vip', models.CharField(default='Sin Dato', max_length=80)),
                ('Funcion', models.CharField(default='Sin Dato', max_length=80)),
                ('Departamento', models.CharField(default='Sin Dato', max_length=80)),
                ('PaisRegion', models.CharField(default='Sin Dato', max_length=80)),
                ('Numero', models.CharField(default='Sin Dato', max_length=80)),
                ('Calle', models.CharField(default='Sin Dato', max_length=60)),
                ('Ciudad', models.CharField(default='Sin Dato', max_length=40)),
                ('Estado', models.CharField(default='Sin Dato', max_length=80)),
                ('CodigoPostal', models.CharField(default='Sin Dato', max_length=10)),
                ('Distrito', models.CharField(default='Sin Dato', max_length=40)),
                ('Edificio', models.CharField(default='Sin Dato', max_length=10)),
                ('Planta', models.CharField(default='Sin Dato', max_length=10)),
                ('PaisExp', models.CharField(default='Sin Dato', max_length=40)),
                ('MedioComunicacion', models.CharField(default='mail@hitec.com', max_length=30)),
                ('RFC', models.CharField(default='XAXX010101000', max_length=60)),
            ],
        ),
    ]
