# Generated by Django 3.1.3 on 2023-09-25 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0002_contactos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direcciones',
            fields=[
                ('IdRegistro', models.AutoField(primary_key=True, serialize=False)),
                ('IdCliente', models.CharField(default='00000000', max_length=50)),
                ('PaisRegion', models.CharField(default='Sin Dato', max_length=80)),
                ('Calle', models.CharField(default='Sin Dato', max_length=60)),
                ('Numero', models.CharField(default='Sin Dato', max_length=10)),
                ('Calle2', models.CharField(default='Sin Dato', max_length=40)),
                ('Ciudad', models.CharField(default='Sin Dato', max_length=40)),
                ('Estado', models.CharField(default='Sin Dato', max_length=80)),
                ('CodigoPostal', models.CharField(default='Sin Dato', max_length=10)),
                ('Distrito', models.CharField(default='Sin Dato', max_length=40)),
                ('CodigoDomFiscal', models.CharField(default='Sin Dato', max_length=80)),
                ('DireccionPrincipal', models.CharField(default='X', max_length=1)),
                ('Entrega', models.CharField(default='X', max_length=1)),
                ('DestinatarioMercEstandar', models.CharField(default='X', max_length=1)),
                ('DestinatarioFactura', models.CharField(default='X', max_length=1)),
                ('Telefono', models.CharField(default='Sin Dato', max_length=40)),
                ('CorreoElectronico', models.CharField(default='Sin Dato', max_length=500)),
                ('SitioWeb', models.CharField(default='Sin Dato', max_length=500)),
            ],
        ),
    ]
