# Generated by Django 3.1.3 on 2023-09-25 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0003_direcciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('CodeId', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('Descrip', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdCountry', models.CharField(max_length=2)),
                ('CodeId', models.CharField(max_length=3)),
                ('Descrip', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RelReg_Edo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_estado', models.IntegerField()),
                ('idRegion', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Sepomex',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('D_codigo', models.CharField(max_length=10)),
                ('D_asenta', models.CharField(max_length=60)),
                ('D_tipo_asenta', models.CharField(max_length=25)),
                ('D_mnpio', models.CharField(max_length=50)),
                ('D_estado', models.CharField(max_length=35)),
                ('D_ciudad', models.CharField(blank=True, max_length=50)),
                ('D_CP', models.CharField(blank=True, max_length=10)),
                ('C_estado', models.IntegerField(null=True)),
                ('D_oficina', models.CharField(blank=True, max_length=10)),
                ('C_CP', models.CharField(blank=True, max_length=10)),
                ('C_tipo_asenta', models.IntegerField()),
                ('C_mnpio', models.IntegerField()),
                ('Id_asenta_opcons', models.IntegerField()),
                ('D_zona', models.CharField(blank=True, max_length=10)),
                ('C_cve_ciudad', models.IntegerField(null=True)),
            ],
        ),
    ]
