# Generated by Django 3.1.3 on 2023-09-27 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0004_country_region_relreg_edo_sepomex'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactos',
            name='Bloqueo',
            field=models.BooleanField(default=False),
        ),
    ]
