# Generated by Django 3.1.3 on 2023-10-02 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0004_country_region_relreg_edo_sepomex'),
    ]

    operations = [
       
    ]
