# Generated by Django 3.1.3 on 2023-10-04 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0005_auto_20231002_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactos',
            name='Bloqueo',
            field=models.BooleanField(default=False),
        ),
    ]
