# Generated by Django 3.1.3 on 2023-10-10 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0007_auto_20231010_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactos',
            name='Bloqueo',
            field=models.BooleanField(default=False),
        ),
    ]
