# Generated by Django 3.1.3 on 2023-09-27 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0007_remove_direcciones_direccionuuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direcciones',
            name='Ciudad',
            field=models.CharField(default='Sin Dato', max_length=80),
        ),
    ]
