# Generated by Django 3.1.3 on 2023-10-10 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0007_auto_20231010_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='Fecha',
            field=models.DateTimeField(default='2023-10-01 00:00:00'),
        ),
    ]
