# Generated by Django 3.1.3 on 2023-09-27 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0008_auto_20230927_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='direcciones',
            name='DireccionUUID',
            field=models.CharField(default='000000000000', max_length=20),
        ),
    ]
