# Generated by Django 3.1.3 on 2023-10-10 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0008_auto_20231010_1718'),
    ]

    operations = [

    ]
