# Generated by Django 3.1.3 on 2023-10-17 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0008_contactos_bloqueo'),
        ('Clientes', '0009_auto_20231010_1719'),
    ]

    operations = [
    ]
