# Generated by Django 3.1.3 on 2023-09-27 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0009_direcciones_direccionuuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='direcciones',
            name='Bloqueo',
            field=models.BooleanField(default=False),
        ),
    ]
