# Generated by Django 3.1.3 on 2023-10-24 16:37

from django.db import migrations, models


class Migration(migrations.Migration):


    operations = [
        migrations.CreateModel(
            name='divisionCliente',
            fields=[
                ('IdRegistro', models.AutoField(primary_key=True, serialize=False)),
                ('IdContacto', models.CharField(default='0000000', max_length=80)),
                ('IdDivision', models.CharField(default='0000000', max_length=80)),
                ('IdSubdivision', models.CharField(default='0000000', max_length=80)),
            ],
        ),
        migrations.AlterField(
            model_name='log',
            name='Fecha',
            field=models.DateTimeField(default='2023-10-01 00:00:00'),
        ),
    ]
